### ISSUE TITLE
Test fund manager

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#14]
Add tests to all fundManager.cairo contract functions

**Comment by renzobanegass** [comment]
Hey, can I work on this? It should be fast.

**Comment by adrianvrj** [comment]
Hi @renzobanegass unfortunately we do not have enough resources to pay our contributors yet, would you still like to participate?

**Comment by renzobanegass** [comment]
Don't worry I understand, I still want to contribute to the project.

**Comment by renzobanegass** [comment]
Nice, I'll start ASAP

**Comment by adrianvrj** [comment]
Ty very much, make sure to read contributors guide and feel free to contact me or @EmmanuelAR for any doubts you may have

**Comment by adrianvrj** [comment]
Hi @renzobanegass any updates on this?

**Comment by renzobanegass** [comment]
Hi, sorry for the delay I had trouble finding the correct setup for this and I've been busy with other things, I already have the tests but they are failing because I'm missing something, I probably have the wrong version of snforge which is what I'm using for testing so I'll try using the same version as the [docs ](https://book.starknet.io/ch02-13-foundry-forge.html). You can expect a PR by tomorrow.

**Comment by adrianvrj** [comment]
No worries, we made some changes to the code you may want to check out

**Comment by diegoTech14** [comment]
Hello @adrianvrj I would like to help with this issue, can I take it?

**Comment by EmmanuelAR** [comment]
lets go @diegoTech14

**Comment by diegoTech14** [comment]
Thank you bro!
