### ISSUE TITLE
[fix] Refactor navBarItems

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#163]
### This issue will be part of ODHack9.0, please apply via Onlydust app
- This is a frontend issue, knowledge in Nextjs is recommended.
- Currently we are using a constant to set the navbar items in every single page, this constant appears in every single component that needs the navbar.
- Create a new constant on the constants directory with the values for the navbar items.
- Refactor each component that uses the navItems to use the constant created.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by PoulavBhowmick03** [comment]
I'd like to take it up

I'm Poulav Bhowmick, a Starknet Wolf. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet, Ethereum, Stellar ecosystem. 

### Approach

**Comment by Iwueseiter** [comment]
Could I take over this issue?
I'm a frontend and smart contract developer. I will create a navbar and refactor every component that uses the navitem to use the constant I'd create.
I will make it responsive and make sure it functions as expected

**Comment by SoarinSkySagar** [comment]
My background:
I am a full stack web developer  with 3 years of experience in TS and JS, and 2 years specifically with Next.js
Approach:
I would create a new constant in the frontend/gostarkme-web/constants/index.ts, and then I will refactor each component to use this constant (from index.ts)

Would love to take up this issue!
ETA: 1 Hour

**Comment by TEMHITHORPHE** [comment]
Could I be assigned to this?
Template:
Hi, I'm Temi and I'll be working on issue #163

I estimate this will take 30 minutes to complete.

This is how I would tackle this issue:
I'll declare the constants value in the constants file (will create if it doesn't exist), 
this ensures we have a single source of truth, helps simplify future refractors.

**Comment by Iwueseiter** [comment]
Can I tackle this one?

I'm a frontend and smart contract developer. I will create s constant navbar and also refactor every component that uses the narvitem to use the constant I'd create.
This will be my first time contributing to this project and I'm looking forward to working.
ETA: 24hrs

**Comment by wheval** [comment]
Can I handle this task? ETA is 1 day.

**Comment by Benjtalkshow** [comment]
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

Currently, the navigation bar items are individually set in each pages `(myfunds/page.tsx, myprofile/page.tsx, app/page.tsx)` that uses them, with code that defines navItems like this:

`const navItems = [
    { label: 'My Profile', href: `/app/myprofile` },
    { label: 'My Funds', href: `/app/myfunds` }
];`

To address this, I plan to centralize the `navItems` constant within the constants directory, specifically in `constants/index.ts`, so that all components can reference the same constant without redefining it locally. Each component will import navItems from this single source, reducing repetition, ensuring consistency, and making future updates simpler and more maintainable.

This will be my first contribution to the project, and I’m excited to apply my skills to enhance the code structure and efficiency in this way. Once implemented, I’ll thoroughly test the refactor to confirm the navigation bar functions as expected across all components.
My ETA is 5hrs when the task is assigned to me. Thanks

**Comment by mimisavage** [comment]
Can I take care of this issue?

**Comment by MrRoudyk** [comment]
I'd like to take this issue.

About me:
Software Engineer with 10 years of experience. For the past 5 years, I’ve specialized in HR Tech solutions. I’m passionate about exploring new technologies and currently looking to deepen my expertise in blockchain, smart contracts, and decentralized applications. I have also contributed to open source development at OnlyDust ([My OnlyDust Profile](https://app.onlydust.com/u/MrRoudyk)).

**Comment by LazarusAA** [comment]
I am applying to this issue via [OnlyDust platform](https://www.onlydust.com/).

## My background and how it can be leveraged

Hi, I'm Alvaro Lazarus a new member of Dojo Coding, im relativley new to blockchain but I recently worked on a project for a Hackathon where I used Nextjs extensively which makes me confident that I can complete this issue.

## How I plan on tackling this issue

- Id move navbar items to a single constant in the constants directory.
- And update all components to reference the new constant for navbar items.

Please consider 

ETA: 48 hrs

**Comment by GradleD** [comment]
Would love to tackle this! I am going to commit directly on github

**Comment by Akshola00** [comment]
May I handle this issue?

**Comment by FemiOje** [comment]
Hi, I'm jinius and I'll be working on issue #163.

I estimate this will take 3 hours to complete.

This is how I would tackle this issue:
1. create new const named navItems in frontend/gostarkme-web/constants/index.ts
2. populate const with all needed navbar labels/links.
3. remove hardcoded navItems const from all components importing Navbar(eg frontend/gostarkme-web/components/ui/Bounded.tsx), and replace with navItems in frontend/gostarkme-web/constants/index.ts
4. test for functionality and responsiveness.

**Comment by FemiOje** [comment]
I am applying to this issue via OnlyDust platform.

Hi, I'm jinius and I'll be working on issue #163.

I estimate this will take 3 hours to complete.

This is how I would tackle this issue:
1. create new const named navItems in frontend/gostarkme-web/constants/index.ts
2. populate const with all needed navbar labels/links.
3. remove hardcoded navItems const from all components importing Navbar(eg frontend/gostarkme-web/components/ui/Bounded.tsx), and replace with navItems in frontend/gostarkme-web/constants/index.ts
4. test for functionality and responsiveness.
