### ISSUE TITLE
[fix] Update contracts variable and function names

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#193]
**Is your feature request related to a problem? Please describe.**
Currently we are using mixed snake and camel case for the functions and variables names.

**Describe the solution you'd like**
In cairo, camel case is normally used, please update all of the variable and functions that use camel case to use snake case

**Comment by raizo07** [comment]
@adrianvrj can I work on this

**Comment by anonfedora** [comment]
I'm Eleazar, a fullstack Blockchain developer, Can I take this from here?

**Comment by jaiminRaiyani** [comment]
Let me handle this issue!

**Comment by Iwueseiter** [comment]
Hi @adrianvrj, can I work on this?

**Comment by martinvibes** [comment]
May I be assigned to this?
Please kindly assign

**Comment by No-bodyq** [comment]
May I take care of this?
ETA is one day

**Comment by NueloSE** [comment]
I'd like to handle this task.

**Comment by Akshola00** [comment]
I’d like to resolve this.
i would find all the places that snake casing is being used and I will change all functions and variables to camel casing
please assign this to me :)

**Comment by tasneemtoolba** [comment]
I would like to contribute further in this project! So such a task would help me familiarise myself with the project itself and its structure

**Comment by ShantelPeters** [comment]
Can i please be assigned to this issue @adrianvrj

**Comment by casweeney** [comment]
I can quickly tackle on this issue.

I will update the functions and variable names this will also affect the test cases; therefore, I will also update the tests to make sure all tests are passing as they should.

**Comment by Kaminar-i** [comment]
hey @adrianvrj i'm a fullstack dev and i would love to work on this issue please kindly assign :)

#### 1. Audit Current Naming Conventions
Start by reviewing all the function and variable names in the codebase, especially focusing on any instances where snake_case is used.
Make a list or mark each function and variable that needs renaming. This helps track what’s changed and reduces the chance of missing anything.

#### 2. Refactor Names to Camel Case
Update each identified snake_case function and variable to camelCase, adhering to Cairo's convention.
Ensure consistency across the board; for instance, set_user_data should become setUserData, and user_address should become userAddress.

#### 3. Ensure No Functional Changes
This issue is solely focused on refactoring names. Be cautious not to alter the function logic or parameters in any other way.
Make sure you’re only changing names and not unintentionally modifying functionality.

#### 4. Review and Test
After renaming, review each change thoroughly to ensure all instances are updated. Use “Find and Replace” as needed.
Run tests to confirm everything functions as expected after the refactor. Unit tests and integration tests should still pass, verifying that the changes are superficial (naming-only) rather than functional.

Eta: 12hrs

**Comment by Mystic-Nayy** [comment]
@adrianvrj can I please work on this?

**Comment by pheobeayo** [comment]
Mind if I try this one?

**Comment by derianrddev** [comment]
Hi, I'm Derian, a fullstack developer and member of Dojo Coding, and I will be working on issue #193.

I estimate it will take me 12 hours to complete.

Here's how I will approach this issue: I would change all variables and functions that are in camel case to snake case, following the Cairo style standard.

**Comment by joanne-cmd** [comment]
Hello, my name is Joanne. I would love to work on this issue. I have a strong background in Rust and a good understanding of Cairo, and I am familiar with the concept of snake_case. I look forward to working on these issue.

**Comment by jorgezerpa** [comment]
hello! @adrianvrj can I take this? should be fast

**Comment by wheval** [comment]
Hello @adrianvrj,
I'm Wheval, a Frontend developer and Cairo developer.

To solve this issue, I would change each variable and function name to use Camel Case (like this,  functionName). I would also update imports to the changed camel case names to ensure consistent camel case naming. 
I would also avoid altering any function logic.
Finally, i would ensure all tests passes and nothing breaks.
I would love to work on this. Thank you.

ETA is 5 hours.

**Comment by Kaminar-i** [comment]
Please, is this still available ?

**Comment by EmmanuelAR** [comment]
@sotoJ24 any update on this issue?

**Comment by PedroCo3lho** [comment]
Hello @EmmanuelAR, is this issue still open for collaboration? Please let me know, and I’ll raise a PR by tomorrow.
