### ISSUE TITLE
[test] Add test for new method update_receive_donation

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#209]
- [ ] Add test for new method update_receive_donation in contracts/src/fund.cairo

**Comment by Iwueseiter** [comment]
Hi @EmmanuelAR can I work on this?

**Comment by Benjtalkshow** [comment]
Can I contribute to this one?

**Comment by NueloSE** [comment]
Could I be assigned to this?

**Comment by No-bodyq** [comment]
Can I handle this task?

**Comment by petersdt** [comment]
I can work on this ETA <= 24hrs

**Comment by casweeney** [comment]
I am an experienced Cairo developer who has written and tested complex Cairo smart contracts.

I can handle this task.

## ETA: 6 hours

**Comment by anihdev** [comment]
I’m interested in this one.
im very advanced in cairo and can provide a very robust test suite for this

**Comment by martinvibes** [comment]
hey @EmmanuelAR i'm a blockchain developer and I'd like to take this issue.
kindly assign :)

**Comment by mayasimi** [comment]
I can handle this task kindly assign me ETA <=24hrs

**Comment by wheval** [comment]
Hello @emmanuelar ,

I'm wheval. A frontend dev and cairo developer.
Can I handle this task? I would test all case scenarios for the update_recieve_donation method.
I would also ensure that all tests passes and follow the current code structure.

Thank you. 
ETA is 1day.

**Comment by dev-chinx** [comment]
holla @EmmanuelAR mind if i take on this issue :)
i would love to be a contributor on your project

**Comment by Michaelkingsdev** [comment]
@EmmanuelAR 
Please permit me to take care of this. 48hrs max

**Comment by derianrddev** [comment]
Hi, I'm Derian, I'm a software engineer focused on fullstack web development and I'm currently part of Dojo Coding. I have been studying Cairo through the Starknet Bootcamp, completed all the Starklings exercises, and have been practicing on Node Guardians. I would like to work on this issue and gain more experience.

I estimate this will take 1 day to complete. 

This is how I would tackle this issue:
- Create a unit test in the corresponding test file.
- Initialize the contract.
- Call update_receive_donation with different input values.
- Verify that the contract state updates correctly using assertions in the test.

**Comment by ShantelPeters** [comment]
Hi @EmmanuelAR please can I be assigned to this issue 
This would be my first time contributing to this repo

**Comment by Kaminar-i** [comment]
I'd love to give this a go @EmmanuelAR mind if i take on this issue :)

**Comment by Akshola00** [comment]
Can I work on this

**Comment by sasasamaes** [comment]
I'd like to handle this task.
	1.	Understand the Purpose of update_receive_donation:
Review the update_receive_donation method in fund.cairo to identify what it does. Common scenarios might include updating internal states, setting new values, or modifying parameters related to receiving donations.
	2.	Set Up Initial Conditions:
Initialize any required variables and contract instances for the test. If update_receive_donation relies on a specific initial state or parameters, set those before calling the method.
	3.	Invoke update_receive_donation:
Call the update_receive_donation method with the parameters it expects. These could be donation amounts, addresses, or other values, depending on the method’s requirements.
	4.	Verify the Expected Results:
After calling update_receive_donation, assert the expected changes in state. This may involve checking updated values, balances, or any flags set by the method.
ETA: 1 Day

**Comment by GradleD** [comment]
Is it okay if I take this?

**Comment by aguilar1x** [comment]
I am a software developer. I am also a member of Dojo Coding, where I am expanding my experience in Cairo and Web3 technologies. I am excited to learn and be part of this project with my second contribution on onlydust. To approach this test, I would take the following steps: 

1. Project review: I will analyze the test in detail to understand its structure and functionality. 

2. Clone repository: The repository of the principal will be cloned in my main to be able to work it and complete the method update_receive_donation test 

3. Check the execution steps: The scenarios where they can be included will be evaluated, update internal states, establish new values or modify parameters related to the receipt of donations, so that it works in the best way. Just as they will be configured in such a way that everything has coherence and the code does not collapse, so the changes will be verified and variables, values, etc. will be added if necessary for the test to be in operation. 

4. Final review: A final review will be performed to ensure that the Test update_receive_donation is workable with respect to the mainteiner and issue indications. So if there is any doubt or change I am attentive to updates to the issue. 

5. Time: 1 day ETA
