### ISSUE TITLE
[test] Add test_withdraw test for withdraw methods

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#210]
- [ ] ⁠Add test_withdraw test for withdraw methods in contracts/src/fund.cairo

**Notes (PLEASE READ)**

1.⁠ ⁠Withdraw method was already test but we remove receive_donation method so we have to refresh the withdraw test.
2.⁠ ⁠In contracts/tests/test_fund.cairo file there are the past wothdraw methods commented, I leave it there so you can take reference.

**Comment by ooochoche** [comment]
I would love to work on this

**Comment by Snehagupta1907** [comment]
Let me try this one! i have worked on testing side as well

**Comment by ooochoche** [comment]
I would love to work on this, I've read through the description and can work on the issue

**Comment by Mystic-Nayy** [comment]
I’d like to work on this please.
can i be assigned ?

**Comment by NueloSE** [comment]
May I pick this up?

**Comment by petersdt** [comment]
I can work on this ETA <= 24hrs

**Comment by casweeney** [comment]
Can I jump on this task?I am an experienced Cairo developer who has written and tested complex Cairo smart contracts.

I can handle this task.

## ETA: 5 hours

**Comment by No-bodyq** [comment]
I'd love to give this a go.
I am a smart contractor and fullstack developer 
I would love to contribute to this project

**Comment by anihdev** [comment]
Can I contribute to this one?

**Comment by martinvibes** [comment]
hey @EmmanuelAR i'm a blockchain dev and I'd like to take this issue.
kindly assign :)

**Comment by dev-chinx** [comment]
holla @EmmanuelAR mind if i take on this issue :)
i would love to be a contributor on your project

**Comment by Kaminar-i** [comment]
I'd love to give this a go @EmmanuelAR mind if i take on this issue :)

**Comment by ShantelPeters** [comment]
Please can I work on this @EmmanuelAR ?

**Comment by sasasamaes** [comment]
Could I take on this issue?
	1.	Review the Updated withdraw Method Logic:
Since the receive_donation method has been removed, ensure that you understand any changes in how withdraw should function. Verify that all parameters and any preconditions (like balance checks) are correctly updated in the contract logic.
	2.	Use the Existing Comments as Reference:
In the contracts/tests/test_fund.cairo file, locate the previous, commented-out withdraw tests. These should help you understand the structure and assertions that were used in the original tests, giving you a starting point for rebuilding the test in the current context.
	3.	Set Up the test_withdraw Test:
	•	Initialize any required variables or states in your test, such as contract instances and initial balances.
	•	Call the withdraw method with appropriate parameters.
	•	Assert that the expected state changes occur after withdrawal, such as reduced balance in the contract and possibly increased balance in the recipient’s account.
	4.	Verify Assertions in the test_withdraw Test:
Ensure that the new test includes the necessary assertions for balance verification and any other relevant effects of withdraw. If the withdraw method emits an event, include an assertion to verify that the event is correctly emitted.
ETA: 1 Day
