### ISSUE TITLE
Add dashboard page

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#39]
The dashboard page is the page where the user lands after clicking 'Go to app' btn, check the Figma design to see what we want it to look like.

For this issue we only want the html and style necessary for the page to look exactly like the figma design, retrieving the fundings will be another issue.

**Comment by ooochoche** [comment]
@adrianvrj do you still need help with this?

**Comment by adrianvrj** [comment]
Hi @ooochoche are you willing to help? 
Unfortunately we don't have enough resources to pay our contributors but I can go ahead and assign it to you!

**Comment by Sarvadnyaawaghad150503** [comment]
Hello can you assign me to do this work , i will complete by this week

**Comment by adrianvrj** [comment]
Hello @Sarvadnyaawaghad150503 unfortunately we do not have enough resources to pay our contributors yet, would you still like to work on this?

If so, could you add a description on how you plan to solve this issue?

**Comment by ShubhamPatilSp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Educational Background: I hold a Bachelor’s degree in Computer Applications.

Full-Stack Web Development: Experienced in the MERN stack, building scalable and user-friendly applications.

Key Projects:

Traveller: A travel platform inspired by Airbnb, with dynamic authentication and image management.
Live Demo - https://traveller-node.onrender.com/listings

Portfolio Website: A personal portfolio showcasing modern UI and interactive features.
Live Demo - https://my-portfolio-mauve-one.vercel.app/

VirtualR: A React-based VR design project with drag-and-drop functionality and real-time updates.
Live Demo - https://virtualr-main-git-main-shubhampatilsps-projects.vercel.app/

Skills:

Backend: Node.js, Express.js, MongoDB, Mongoose, Passport.js
Frontend: Next.js, React.js, HTML, CSS, Tailwind, Bootstrap
How It Can Be Leveraged: My background enables me to create robust, scalable applications that drive results across the stack.



### How I plan on tackling this issue
Understand: Figure out what the problem is and gather all the information.
Research: Look into possible solutions and plan the best approach.
Try: Implement the solution on a small scale first.
Test & Adjust: Check if it works and make any necessary changes.
Document: Write down what was done and what I learned.
I’m excited to use this approach to tackle challenges.

**Comment by MayowaObisesan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a web3 frontend developer with full-stack experience.
I have worked on various frontend projects building exciting and captivating UI for good User Experience. I believe in pixel-perfect design and UI implementations.
I have a knack for building amazing web and mobile UI.

### How I plan on tackling this issue
Once I have understood the problem, I will fork the repo, and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, I raise the PR the same day.

I would like to work on this issue because I love what the project is about.

**Comment by Sarvadnyaawaghad150503** [comment]
@adrianvrj  Its ok for me to work for free, please assign me the part you want me to work on, i can complete task in time frame of one week

**Comment by MayowaObisesan** [comment]
Hey @adrianvrj .
I am ready to pick up this task and finish it today if it's still available.

**Comment by adrianvrj** [comment]
Closing this since we need to reorganize the focus
