### ISSUE TITLE
Add project support card

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#45]
Add the following design to the root page of the project, should be right down after scrolling the main content:

![Welcome page (scroll)](https://github.com/user-attachments/assets/839aa934-29a9-4a77-bccb-ee5100fa8c85)

Consider that the btns should not redirect to any url since the urls we want them to go to are not implemented yet

**Comment by Gift-Naomi** [comment]
@adrianvrj Can i please work on this issue?

**Comment by adrianvrj** [comment]
Hi @Gift-Naomi unfortunately we do not have enough resources to pay our contributors, would you still like to work on this?
If so, could you please add a description on how you plan to tackle this issue and the time estimate

**Comment by ShubhamPatilSp** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Educational Background: I hold a Bachelor’s degree in Computer Applications.

Full-Stack Web Development: Experienced in the MERN stack, building scalable and user-friendly applications.

Key Projects:

Traveller: A travel platform inspired by Airbnb, with dynamic authentication and image management.
Live Demo - https://traveller-node.onrender.com/listings

Portfolio Website: A personal portfolio showcasing modern UI and interactive features.
Live Demo - https://my-portfolio-mauve-one.vercel.app/

VirtualR: A React-based VR design project with drag-and-drop functionality and real-time updates.
Live Demo - https://virtualr-main-git-main-shubhampatilsps-projects.vercel.app/

Skills:

Backend: Node.js, Express.js, MongoDB, Mongoose, Passport.js
Frontend: Next.js, React.js, HTML, CSS, Tailwind, Bootstrap
How It Can Be Leveraged: My background enables me to create robust, scalable applications that drive results across the stack.

### How I plan on tackling this issue
Understand: Figure out what the problem is and gather all the information.
Research: Look into possible solutions and plan the best approach.
Try: Implement the solution on a small scale first.
Test & Adjust: Check if it works and make any necessary changes.
Document: Write down what was done and what I learned.
I’m excited to use this approach to tackle challenges.

**Comment by ShantelPeters** [comment]
Hi @adrianvrj  I will love to work on this

**Comment by martinvibes** [comment]
hello @adrianvrj i would love to work on this issue and contribute to your repo if you give me the opportunity

**Comment by MayowaObisesan** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a web3 frontend developer with full-stack experience.
I have worked on various frontend projects building exciting and captivating UI for good User Experience. I believe in pixel-perfect design and UI implementations.
I have a knack for building amazing web and mobile UI.

### How I plan on tackling this issue
Once I have understood the problem, I will fork the repo, and simulate the issue that was described. Depending on the complexity of the issue. If it is a frontend issue with an easy tag, I can raise a PR in minutes, but for more complex UI, I raise the PR the same day.

I would like to work on this issue because I love what the project is about.

**Comment by MayowaObisesan** [comment]
If you accept me to work on the issue, I can raise a PR immediately.
Because I'm done with the issue.

**Comment by adrianvrj** [comment]
Assigning @MayowaObisesan since he already did some work on this, next time please wait to be assigned to work on the issue so we do not waste any effort.

**Comment by MayowaObisesan** [comment]
Apologies. I will wait for next time.
Thanks.

**Comment by MayowaObisesan** [comment]
Hi @adrianvrj. Kindly review the PR I raised.

**Comment by MayowaObisesan** [comment]
Hi @adrianvrj .
I have added a screenshot to the PR description as you requested.
