### ISSUE TITLE
[CI] Fix CI Backend Pipeline

### ISSUE THREAD

**Issue by EmmanuelAR** [web3wagers/gostarkme#91]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- The CI pipeline for the backend is currently broken. Please install Scarb and add the following steps: scarb build, scarb fmt, and sngforce test.
- Knowledge in CI/CD with snforge and scarb is recommended.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by raizo07** [comment]
I'll like to work on this

**Comment by bitfalt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hii! My name is Daniel, I’m a Computer Science student and web3 developer. I’ve done some contributions, finished a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings and I have participated in multiple Hackathons. I’m also a member of the Dojo Coding community. I’ve recently learned about GitHub Actions and the multiple functionalities it has.

### How I plan on tackling this issue
I would approach this issue is in the following way:
- Since the error is due to the scarb installation, I would search for a way to install scarb properly.
- Check in my fork that everything works perfectly for PRs which is when the tests are being run
- I would ask the maintainers if any question come up during my testing.

**Comment by raizo07** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. 

I'm a software Dev with over four years experience and have worked on a couple of projects here. Here's a link to my profile https://app.onlydust.com/u/raizo07


ETA: One day

**Comment by JoE11-y** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
With over four years in blockchain and backend development, I’ve worked across different ecosystems, handling everything from smart contract design to on-chain interactions and protocol integration. I focus on building secure, scalable, and reliable blockchain applications, managing both on-chain and off-chain infrastructure.

### How I plan on tackling this issue
I'd review the logic behind the pipeline failure to identify what’s causing it to malfunction, then proceed with implementing a fix.

**Comment by GoSTEAN** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged


I have experience in CI/CD pipelines, particularly with tools like Scarb and snforge. My background in backend development, smart contracts, and automated testing makes me adept at resolving issues in continuous integration processes. I've worked with similar toolchains and am confident in debugging and optimizing broken pipelines.





### How I plan on tackling this issue
I would start by reading the contributor's guide to understand the project’s best practices. Next, I’d install Scarb and ensure the required versions of the tools are set up. I'd then integrate the `scarb build`, `scarb fmt`, and `snforge test` steps into the CI pipeline, testing each to ensure the backend build and test processes run smoothly.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will start by fixing the CI backend pipeline, as it involves understanding CI/CD processes and potential dependencies. 

  

- **Step 1:** I will review the CI pipeline logs to identify specific errors and failures. 

  

- **Step 2:** I will install Scarb and ensure it's configured correctly for the project. 

  

- **Step 3:** I will add the necessary steps: `scarb build`, `scarb fmt`, and `sngforce test` to the pipeline configuration. 

  

- **Step 4:** I will test the pipeline after making these changes to verify that it runs successfully without errors. 

  

- **Step 5:** I will document the changes made to the CI configuration for future reference.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello  I am Joseph I am a software developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute.

### How I plan on tackling this issue
I will fix the CI backend pipeline by installing scarb and adding the required steps I have knowledge of Scarb and Snorge I used them in a previous project here on onlydust  I should be done in 3-4 days

**Comment by lindsaymoralesb** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi! My name is Lindsay, and I'm a Software Engineer based in Costa Rica. I've already successfully contributed to the last 4 ODHacks in various projects, feel free to check my profile and contributions.

I've been working over the past 4.5 years as a full stack developer, specializing myself in frontend development.

I’ve also had the opportunity to work on the ci cd and github actions of several projects. In fact, in some of the odhacks I helped a couple of projects (carbonable and influence sdk) with their github actions, both creating new ones and fixing existing ones.

### How I plan on tackling this issue
First I would check the current stats and logs of the github actions to spot the issue.
After that I’ll use a tool like act to be able to run the github actions locally to debug and apply fixes.

After the fix is applied I will run the action both locally and in my forked repo to make sure I works as expected before pushing to the main repo.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
**Fix CI Pipeline for Backend**

Hello Go Stark Me team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of the issue to **Fix the CI pipeline for the backend**. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
#### Implementation Plan

**STEP 1:** Analyze the current CI pipeline configuration.  
*Description:* I will review the existing CI pipeline configuration files to identify where the pipeline is broken and how it is currently set up.

**STEP 2:** Install Scarb.  
*Description:* I will install Scarb, ensuring that it is properly set up in the environment. This might involve using a package manager or downloading it directly from the official source. 

```bash
# Example command to install Scarb (assuming it's available via a package manager)
cargo install scarb
```

**STEP 3:** Add necessary CI steps.  
*Description:* I will modify the CI configuration file (e.g., `.github/workflows/ci.yml` or similar) to include the required steps: `scarb build`, `scarb fmt`, and `sngforce test`. Here's an example of how these steps might be integrated:

```yaml
name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Scarb
        run: |
          cargo install scarb

      - name: Build project
        run: scarb build

      - name: Format code
        run: scarb fmt

      - name: Run tests
        run: sngforce test
```

**STEP 4:** Test the CI pipeline.  
*Description:* After making the changes, I will trigger the CI pipeline to ensure that it builds correctly and that all tests pass. If there are any errors, I will address them promptly.

**STEP 5:** Document changes.  
*Description:* I will update the documentation related to the CI pipeline, if necessary, to reflect the new steps and any installation instructions for Scarb.

### Goal
The goal is to restore the CI pipeline functionality for the backend by correctly integrating Scarb and ensuring that the build, format, and test steps are working as expected.

I look forward to your feedback on my approach!

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
i am a frontend and blockchain developer ,i have experience with tools like scrab and snforge , with my background it shows i can adapt quickly and contribute effectively so i will like to take up this issue. kindly assign

### How I plan on tackling this issue
To solve the issue, i will  install Scarb in the CI pipeline. Then, add the steps: scarb build, scarb fmt, and snforge test to the pipeline configuration. And then ensure that CI/CD with snforge and Scarb is correctly set up and running. i will ask the maintainers for help if any question comes up during my testing
