### ISSUE TITLE
[feat] Add New Fund page

### ISSUE THREAD

**Issue by adrianvrj** [web3wagers/gostarkme#95]
### This issue will be part of ODHack8.0, please apply via Onlydust app
- Create a new page which route will be: /app/newfunding, this page should be the new fund page, please note that there are two different stages in this form like page, please develop both of those stages.
- Take a look at the figma to see how the dashboard page looks like.  [Figma prototype](https://www.figma.com/design/SCiGViaoPT9UTrT7CsLbAt/Go-Stark-Me?node-id=0-1&t=FUhnIhNcXRIGkQ16-1)
- Do not worry about functionality yet, we only want to develop the design.
- Knowledge in Nextjs and typescript are recommended.
- Please read [contributors guide](https://github.com/web3wagers/gostarkme/blob/dev/CONTRIBUTORS_GUIDE.md) before asking for an issue.

**Comment by Ayoazeez26** [comment]
Hi @adrianvrj can I work on this?

**Comment by martinvibes** [comment]
hello @dmirgaleev i am a frontend dev and blockchain developer
please can i work on this issue :) and would love to be a contributor

**Comment by wugalde19** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi team,
I’m William from Costa Rica 🇨🇷 and a member of the Dojo Coding community.
I am interested in contributing to this issue and believe my skills and background make me well-suited for the task. I’ve worked over 7 years as a Full-Stack engineer in several technologies including the ones used on this project Typescript and NextJs (NextJs mostly on web3 projects that I’ve contributed in both Hackathons and OD Hacks)

Profiles:
https://app.onlydust.com/u/wugalde19
https://github.com/wugalde19


### How I plan on tackling this issue
The way I’d approach this is by checking the Figma file to understand the components and how the page should look like. As you guys mentioned in the issue description, the implementation will be pure UI components without any functionality yet. Once I know what needs to be built, then I’ll go and create the new route (folder and page.tsx) for /app/newfunding, on that new page I’ll add the two stages of the form.


I’m interested in learning more about your team and looking forward to contributing to this project.

**Comment by BernalHQ** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, my name is Bernal, and I’m a software developer with four years of experience. I’m passionate about contributing to projects and learn, and I would love the opportunity to contribute to this project

### How I plan on tackling this issue
First, I will verify the design in the Figma file to ensure alignment with the project’s requirements. Then, I’ll build the Fund page in the project. Afterward, I’ll run UI tests to confirm that everything is working as expected.

**Comment by devcollinss** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack developer. Nextjs, Cairo, nodej, react.

### How I plan on tackling this issue
I will create an app/newfunding/page.tsx
Implement the UI, making sure develop the two stages on the form and following best practices.

**Comment by evgongora** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm Erick and I'll be working on issue #94.
I have experience working with Next.js and TypeScript, which aligns with the requirements of this issue. I have also worked on developing UI components and integrating design elements from Figma into web applications. My background as a web development student at Dojo Coding will help ensure that the page is implemented efficiently and follows best practices. I estimate this will take around 2 days to complete.

### How I plan on tackling this issue
Here's how I plan to tackle this issue:

Review the Figma prototype to fully understand the layout and design of the fund details page.
Set up the route /app/fund/{fundid} in the Next.js project to handle the dynamic fund ID.
Create the fund details page layout, ensuring both funding state scenarios are handled visually, without adding functionality at this stage.
Follow the design guidelines from Figma to ensure consistency and ensure the design matches the prototype as closely as possible.
Focus on styling to ensure the design is fully responsive and maintains visual consistency across different screen sizes.
Perform a self-review before submitting the pull request to ensure the page looks consistent with the Figma prototype.

**Comment by pablomadrigal** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I’m Pablo Madrigal, I have 7+ years of experience working with React and NextJs. I’m pretty new in the web3 world, I just joined Dojo Coding a couple of weeks ago and have been learning a lot about Cairo and web3 development. Pretty excited to start contributing on Only Dust

### How I plan on tackling this issue
I already review the Figma file. So I will create a new page on Next with the form using the 2 steps shown on the design, using tailwind

**Comment by Mario-Araya** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hii! My name is Mario Araya, I’m a Software Developer with 2+ years of experience. I have worked with backend technologies such as Cairo, Java, and C#, as well as frontend development using React, NextJS, and JavaScript/TypeScript. I’ve made contributions to open-source projects, completed a Starknet Bootcamp, exercises on NodeGuardians, finished Starklings, and participated in multiple hackathons. I’m also a member of the Dojo Coding community here in Costa Rica.

### How I plan on tackling this issue
I would approach this task by creating a new page with the route /app/newfunding, which will serve as the new fund page featuring two distinct stages as outlined in the Figma prototype for the dashboard. My focus would be solely on replicating the design elements without implementing any functionality at this stage. Given the requirement for knowledge in Next.js and TypeScript, I would ensure that the page is built using these technologies while adhering to the project's contributor guidelines before seeking further assistance or clarification on the issue.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi @adrianvrj,

I’m Benjamin, a JavaScript developer with 4 years of experience and over 18 contributions on OnlyDust | https://app.onlydust.com/u/Benjtalkshow. I specialize in crafting responsive and user-friendly interfaces using Next.js and Svelte, and I’m excited about the chance to work on the new funding page for Go Stark Me project.

### How I plan on tackling this issue
For this task, I’ll be creating a page at the route /app/newfunding, which will be our new fund page. I see that there are two different stages in the form layout, and I’ll make sure to develop both of those stages to match the design you provided in the Figma prototype.

Right now, my main focus will be on nailing the design no need to worry about functionality just yet. I want to ensure that the layout looks great and is user-friendly before we add any interactive elements. I’ll be keeping the Figma design close by to make sure I capture all the details just right.

With my experience in Next.js and TypeScript, I’m confident I can set up a clean and organized structure for the code. I’ll also stick closely to the contributors guide to ensure everything aligns with our project’s style.

Once I wrap up the design for the new funding page, I’ll share it with you for feedback.

**Comment by Ugo-X** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
 

I am a Full Stack blockchain Developer with expertise in Next.js, Nest.js, TypeScript, JavaScript, React, Node.js, Three.js, Solidity and rust. My journey with OnlyDust hackathons began at Edition 1, and I've since made 69 contributions across 14 projects. With my extensive experience on the OnlyDust platform (profile:  https://app.onlydust.com/u/Ugo-X), I've honed my skills in delivering quality solutions under pressure. 

I bring a unique blend of technical proficiency and user-focused design to every project, whether it's crafting immersive 3D experiences or developing smart contracts. My track record shows I can adapt quickly and contribute effectively to diverse challenges. 

As we surf through Edition 8, I'm excited to leverage my skills and hackathon experience to push the boundaries of blockchain development. I'm confident in my ability to tackle new challenges and drive innovation in this space.

### How I plan on tackling this issue
I will create a new fund page that adheres to the design specifications provided. 

  

- **Step 1:** I will set up a new route in the Next.js application for `/app/newfunding`. 

  

- **Step 2:** I will refer to the Figma prototype to understand the layout and design of the new fund page. 

  

- **Step 3:** I will implement the two different stages required for the form-like page. 

  

- **Step 4:** I will ensure the components are structured according to the design specifications. 

  

- **Step 5:** I will apply styles consistent with the design outlined in the Figma prototype. 

  

- **Step 6:** I will run the application to verify that the new fund page renders correctly.

**Comment by josephchimebuka** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello @lukaspetrasek I am Joseph I am a frontend developer and blockchain developer and I am also an active contributor here on only dust here is my profile https://app.onlydust.com/u/josephchimebuka. This is my first time to contribute to this repo ill appreciate the opportunity to contribute. this is a couple of frontend and blockchain projects i have built https://metacrypt.vercel.app/ https://mattedsgn.com/

### How I plan on tackling this issue
I will ensure that all the desccriptions are met by adding the required page in 2-3 days time

**Comment by MariangelaNM** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hello, I'm Mariangela. I'm a software developer specializing in front-end development.

### How I plan on tackling this issue
1. **Create the Route:**
   - In the `/app/newfunding` directory, I will create a new dynamic route for the New Fund page . This route will capture the user's address from the URL to enable dynamic content loading.

2. **Design the New Fund page:**
   - I will implement the design of the  Fund page  based on the Figma prototype provided. My focus will be on accurately reflecting the layout and styling as outlined in the design guide.

3. **Test the Page:**
   - After the implementation, I will thoroughly test the page to ensure it functions correctly. I will also check for responsiveness across various devices and screen sizes to ensure an optimal user experience.

**Comment by melnikga** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Can I take this? I’ve participated in almost every ODHack. I have extensive experience in frontend development. I can handle this task.





### How I plan on tackling this issue
In all the projects I worked on during ODHacks, I used Next.js, so implementing this page will be easy for me.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a blockchain developer, i am also an active contributor, i am avaliable to work kindly assign me.

### How I plan on tackling this issue
I will approach the problem by creating a new page at the route /app/newfunding in the Next.js application, implementing the design for both stages of the funding form as outlined in the Figma prototype. Focus solely on the visual aspects without implementing functionality, ensuring the design aligns with the existing dashboard layout. Familiarity with TypeScript and adherence to the contributor's guide are essential for this task.

**Comment by Solomonsolomonsolomon** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Fullstack typescript developer 3+ years

### How I plan on tackling this issue
I will create a new page and route it to /app/newfunding using next ts. I'll use the figma design to ensure pixel perfect designs

**Comment by abdegenius** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a skilled fullstack developer with a wealth of experience in both frontend and backend JavaScript as well as my knowledge of Rustlang, With a solid foundation in testing,I have mastered frameworks like Mocha, Chai, and Jest to ensure robust, reliable code in every project. In addition to traditional web development, I have a strong background in blockchain technology, with hands-on experience in Solidity for Ethereum-based smart contracts. Moreover, I have delved into the emerging world of StarkNet, working with Cairo, a cutting-edge language tailored for STARKs, making them a versatile developer capable of bridging both traditional and decentralized web applications.

### How I plan on tackling this issue
I will complete the replication of the provided figma design into a nextjs page using typescript, making sure to use component based design and write well documented, commented and bug free code.

**Comment by chibokaxavier** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi, I'm a Full-Stack Developer with  over 4 years of experience in building web applications. I specialize in Next.js, React.js, Node.js, Tailwind CSS, and TypeScript, and I've spent the past few years developing everything from sleek, responsive frontends to powerful, efficient backend systems.

What sets me apart is my passion for delivering clean, well-structured code and user-friendly interfaces. I love turning complex problems into elegant, practical solutions. Whether it's crafting dynamic, high-performance applications or integrating robust APIs, I bring a balance of technical know-how and creativity to every project.

### How I plan on tackling this issue
Create the New Funding Page Component
"I will create a new file named NewFunding.tsx inside the pages/app directory. This file will serve as the new funding page."

Multi-Step Form Structure
"I will implement the two stages by using state management in React. I will create a local state, like currentStage, to track which stage of the form is currently active and render different components accordingly."

Design the Two Stages
"Based on the Figma prototype, I will design the layout for both stages:

Stage 1: This stage might include input fields for entering basic funding details such as fund name, amount, or investment type.
Stage 2: This stage will likely include more detailed information about the fund or confirmation of the input provided in the first stage."
Dummy Data for Visualization
"Since functionality is not the focus yet, I will use dummy data to simulate user input, ensuring that the design renders correctly for both stages."

Stage Navigation
"I will implement 'Next' and 'Back' buttons to allow users to navigate between the two stages. These buttons will update the currentStage state to show the appropriate stage."

Styling the Form
"I will use either CSS modules or Tailwind CSS for styling, following the design guidelines in the Figma prototype to ensure visual consistency."

Mobile Responsiveness
"I will ensure the page is mobile-responsive, following modern design best practices to provide a good user experience across devices."

Component Breakdown
"To keep the code clean and maintainable, I will break down the stages into separate components, like StageOne and StageTwo, and then conditionally render them based on the current stage."

Review and Feedback
"Once the design is implemented, I will seek feedback from the team to ensure it aligns with the Figma prototype and meets the design expectations."

**Comment by Rayan9064** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
I am a Full Stack Developer and Cairo Developer. I have good experience building web application. I am new to Open Source and want to begin with this project. I am good in React, Next.js, Typescript, Redux and Context APIs. I can leverage the same to make this a better game for the users. 

### How I plan on tackling this issue
1) Checking the structure of the project and understanding the codebase. 
2) Knowing the tech stack required
3) Finding the area of the problem. 
3) Observe the Figma design. 
4) Implementing into code. 
5) Testing the code by inspecting in different screen size. 
6) Modify the code when not working as expected. 
7) After successful review, create a pull request.

**Comment by JoelVR17** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
**Create a New Funding Page**

Hello Go Stark Me team,

I am Joel Vargas, and I'm a member of Dojo Coding. I also come from OnlyDust.

I would like to request the assignment of the issue to **Create a new page which route will be: /app/newfunding**. Below is my proposed approach for implementing this issue:

### How I plan on tackling this issue
#### Implementation Plan

**STEP 1:** Review the Figma prototype.  
*Description:* I will analyze the provided Figma prototype to understand the design elements and layout of the dashboard page. This will ensure that the new funding page is visually consistent with the rest of the application.

**STEP 2:** Set up the new page route.  
*Description:* I will create a new file `newfunding.tsx` in the `/pages/app/` directory to handle the `/app/newfunding` route. Here’s a basic structure for the new page:

```tsx
// /pages/app/newfunding.tsx
import React from 'react';
import NewFundingForm from '../components/NewFundingForm';

const NewFundingPage: React.FC = () => {
  return (
    <div className="p-6 bg-gray-100">
      <h1 className="text-2xl font-bold">New Funding</h1>
      <NewFundingForm />
    </div>
  );
};

export default NewFundingPage;
```

**STEP 3:** Create the funding form component.  
*Description:* I will develop a reusable component named `NewFundingForm` to handle the two stages of the funding process. The component will be placed in `/components/NewFundingForm.tsx`. Here’s an outline of how the component structure might look:

```tsx
// /components/NewFundingForm.tsx
import React, { useState } from 'react';

const NewFundingForm: React.FC = () => {
  const [stage, setStage] = useState(1); // 1 for stage one, 2 for stage two

  const handleNext = () => {
    if (stage < 2) setStage(stage + 1);
  };

  return (
    <div className="border rounded-md p-4 bg-white shadow-md">
      {stage === 1 && (
        <div className="stage-one">
          <h2 className="text-xl font-semibold">Stage One</h2>
          {/* Stage One Fields */}
          <input type="text" placeholder="Funding Amount" className="border rounded-md p-2 mt-2 w-full" />
          <button 
            onClick={handleNext} 
            className="mt-4 bg-blue-500 text-white rounded-md p-2 hover:bg-blue-600"
          >
            Next
          </button>
        </div>
      )}
      {stage === 2 && (
        <div className="stage-two">
          <h2 className="text-xl font-semibold">Stage Two</h2>
          {/* Stage Two Fields */}
          <input type="text" placeholder="Project Name" className="border rounded-md p-2 mt-2 w-full" />
          <button 
            className="mt-4 bg-green-500 text-white rounded-md p-2 hover:bg-green-600"
          >
            Submit
          </button>
        </div>
      )}
    </div>
  );
};

export default NewFundingForm;
```

**STEP 4:** Review and iterate.  
*Description:* After implementing the design, I will conduct a thorough review to ensure that all elements align with the Figma prototype and the overall application style. Feedback will be sought from the team for any necessary adjustments.

### Goal
The goal is to create a visually appealing and well-structured new funding page that aligns with the existing design of the application, laying the groundwork for future functionality development.

I look forward to your feedback on my approach!

**Comment by jsandinoDev** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-stark-me).

### My background and how it can be leveraged
Hi I'm a fullstack developer from Costa Rica, member of Dojo Coding I have experience working with JavaScript, React, TypeScript, Cairo, Next.js, Node.js.


### How I plan on tackling this issue
I will  create the new component based in the Sigma prototype.
